name: commit workflow
run-name: Executing every commit required actions (tests, static analysis)
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python

        uses: actions/setup-python@v4
        with:
           python-version: '3.12'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Execute unit tests
        run: pytest

      - name: Lint with Ruff
        run: |
          ruff --output-format=github .

        #pip install -r requirements.txt